package pojos;
// Generated 10-Jul-2015 00:28:40 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "library"
)
public class Book implements java.io.Serializable {

    private int id;
    private Member member;
    private String author;
    private String title;
    private int pages;

    public Book() {
    }

    public Book(int id, String author, String title, int pages) {
        this.id = id;
        this.author = author;
        this.title = title;
        this.pages = pages;
    }

    public Book(int id, Member member, String author, String title, int pages) {
        this.id = id;
        this.member = member;
        this.author = author;
        this.title = title;
        this.pages = pages;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "increment")
    @GenericGenerator(name = "increment", strategy = "increment")
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "memberid")
    public Member getMember() {
        return this.member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    @Column(name = "author", nullable = false, length = 45)
    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Column(name = "title", nullable = false, length = 45)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "pages", nullable = false)
    public int getPages() {
        return this.pages;
    }

    public void setPages(int pages) {
        this.pages = pages;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 29 * hash + this.id;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Book other = (Book) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "id=" + id + ", author=" + author + ", title=" + title + ", pages=" + pages;
    }
}
