package pojos;
// Generated 10-Jul-2015 00:28:40 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name="member"
    ,catalog="library"
)
public class Member  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private Set<Book> books = new HashSet<Book>(0);

    public Member() {
    }

	
    public Member(int id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }
    public Member(int id, String name, String email, Set<Book> books) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.books = books;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="member")
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }




}


